### ISSUE TITLE
The notification badge is wrongly displayed for a brief moment when a new tab is opened if the "Home Page" option is active 

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#22]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.
- Have enough history so the "For You" section is populated.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. From Liserlike sidebar hover the "Settings" button.
3. Activate the "Home Page" option.
3. Open a new tab and observe the toolbar button.

[Expected result]:
- The toolbar button is correctly displayed, without the notification badge.

[Actual result]:
- The notification badge is displayed on the toolbar button for a brief moment.

[Notes]:
- Here is a screen recording with this issue:
![laser like - notification badge](https://user-images.githubusercontent.com/31244235/43264363-99022ff8-90ee-11e8-9b77-95e4375159d4.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using latest Laserlike (0.9.32) version and the issue is no longer reproducible.  Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

However, it seems that the green notification badge is displayed when you are on the "Laserlike" homepage, even if there are no stories in the "Read Next" section.
I have logged this scenario in #55 issue.
