### ISSUE TITLE
Emails with foreign characters can't be submitted in the Magic Digest subscription field

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [LaserlikeInc/firefox-addon#29]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Hover the Settings gearwheel button.
3. Type an email address that contains foreign characters and click the "Subscribe" link.
4. Observe the behavior.

[Expected result]:
- Confirm subscription through the submitted email message is displayed.

[Actual result]:
- "network failure" error is displayed inside the field.

[Notes]:
- This issue is not reproducible on the Laserlike Account "Sign In" field, in this case, the email is correctly submitted.
- Attached a screen recording of the issue:

![foreign characters](https://user-images.githubusercontent.com/26000308/43271177-8b371fe4-90ff-11e8-87fc-db1df06e649d.gif)

**Comment by sg-laserlike** [comment]
1. We can't find a popular email provider that allows us to use non-ascii letters in the email address.
2. We use amazon simple email service to send verification code email. Amazon does not support non-ascii email address. It is hard to find an alternative email service provider that support non-ascii email address.

Can we lower this priority or maybe close this since it's very unlikely that we can fix this.

**Comment by chuckharmston** [comment]
I'm fine closing this as a `WONTFIX`; it's a limitation of SES and we're only targeting English-speaking users with this experiment.
